# Generated by Django 4.2.2 on 2023-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=24),
        ),
    ]
