# Generated by Django 4.2.2 on 2023-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_details_alter_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=22),
        ),
    ]
