version: "3"

services:
  backend:
    build:
      context: ./my_todo_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./my_todo_app:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
